In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

import joblib

In [2]:
df=pd.read_csv('tested.csv')

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [4]:

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [5]:
# df=df.drop('Pclass',axis=1)
df=df.drop('Name',axis=1)

In [20]:
df=df.drop('Sex',axis=1)
df=df.drop('Embarked',axis=1)
df
df=df.drop('Ticket',axis=1)
df=df.drop('Cabin',axis=1)
df.isna().sum().sum()
df['Age'].isna().sum()

np.int64(86)

In [21]:
y=df['Survived'].values
X=df.drop('Survived',axis=1)

In [22]:
X_train,X_test,y_train,y_test=train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape

(334, 6)

In [23]:
from sklearn.preprocessing import MinMaxScaler

In [24]:
scaler=MinMaxScaler()

In [26]:
scaler.fit(X_train)

MinMaxScaler()

In [27]:
X_train_scaled=scaler.transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [28]:
X_train_scaled=pd.DataFrame(X_train_scaled,columns=X_train.columns)
X_train_scaled

     PassengerId  Pclass       Age  SibSp  Parch      Fare
0       0.805288     0.5  0.418528  0.000    0.0  0.025374
1       0.072115     0.5  0.312806  0.250    0.0  0.061484
2       0.199519     0.5       NaN  0.000    0.0  0.020901
3       0.687500     0.0  0.312806  0.125    0.0  0.160574
4       0.759615     0.5  0.246729  0.000    0.0  0.020495
..           ...     ...       ...    ...    ...       ...
329     0.168269     1.0  0.273160  0.000    0.0  0.015412
330     0.252404     1.0  0.273160  0.000    0.0  0.015265
331     0.646635     0.0  0.603542  0.000    0.0  0.146862
332     0.834135     0.5  0.312806  0.000    0.0  0.026350
333     0.242788     1.0       NaN  0.000    0.0  0.015127

[334 rows x 6 columns]

In [29]:
X_train_scaled.describe()

       PassengerId      Pclass         Age       SibSp       Parch        Fare
count   334.000000  334.000000  262.000000  334.000000  334.000000  333.000000
mean      0.498345    0.634731    0.393627    0.058757    0.044910    0.072042
std       0.278788    0.422481    0.193680    0.118090    0.104124    0.113315
min       0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
25%       0.272236    0.000000    0.273160    0.000000    0.000000    0.015395
50%       0.498798    1.000000    0.352451    0.000000    0.000000    0.028213
75%       0.732572    1.000000    0.511035    0.125000    0.000000    0.063436
max       1.000000    1.000000    1.000000    1.000000    1.000000    1.000000

In [30]:
regressor=LinearRegression()

In [31]:
regressor.fit(X_train,y_train)

ValueError: Input X contains NaN.
LinearRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values